### ISSUE TITLE
UK_UA

### ISSUE THREAD

**Issue by ELVIS-85** [DmitryLovin/pluginUpdate#3]
{
"modmenu.descriptionTranslation.inventoryhud": "Відображає інвентар на екрані під час гри.",
"key.inventoryhud.category": "Inventory HUD+",
"key.inventoryhud.toggle": "Перемикає режим відображення Inventory HUD+ ON/OFF",
"key.inventoryhud.openconfig": "Відкрити налаштування",
"config.inventoryhud.category.armorhud": "HUD Броні",
"config.inventoryhud.category.inventoryhud": "HUD Івентарю",
"config.inventoryhud.category.potionshud": "HUD Eфектів",
"gui.config.inventoryhud.title": "Inventory HUD+ Налаштування",
"inventoryhud.config.gui.invalpha": "Прозорість:",
"inventoryhud.config.gui.invalpha.tt": "Прозорість заднього тла HUD Інвентарю від 0 до 100",
"inventoryhud.config.gui.invtoggle": "HUD Інвентарю:",
"inventoryhud.config.gui.invtoggle.tt": "Перемикає режим відображення HUD Інвентарю ON/OFF",
"inventoryhud.config.gui.invvert": "Вертикальний режим:",
"inventoryhud.config.gui.invvert.tt.1": "True - Вертикальний режим",
"inventoryhud.config.gui.invvert.tt.2": "False - Горизонтальний режим",
"inventoryhud.config.gui.invmini": "Мінімальний режим:",
"inventoryhud.config.gui.invmini.tt": "Перемикає HUD Інвентарю в мінімальний режим відображення True/False",
"inventoryhud.config.gui.inv.tt": "Опції HUD Інвентарю",
"inventoryhud.config.gui.arm.tt": "Опції HUD Броні",
"inventoryhud.config.gui.pot.tt": "Опції HUD Ефектів",
"inventoryhud.config.gui.pos.tt": "Розташування HUD",
"inventoryhud.config.gui.armtoggle": "HUD Броні:",
"inventoryhud.config.gui.armtoggle.tt": "Перемикає відображення HUD Броні ON/OFF",
"inventoryhud.config.gui.armtype": "Відобразити:",
"inventoryhud.config.gui.armtype.tt": "Перемикає відображення предметів в HUD Броні так/ні",
"inventoryhud.config.gui.armview": "Тип міцності:",
"inventoryhud.config.gui.armview.tt": "Відобразити міцність в:",
"inventoryhud.config.gui.armview.tt.1": "PERCENTAGE - міцність у процентах від 0 до 100.",
"inventoryhud.config.gui.armview.tt.2": "DAMAGE - Скільки пошкодження було нанесено предмету.",
"inventoryhud.config.gui.armview.tt.3": "DAMAGE_LEFT - Скільки шкоди предмет може витримати перед поломкою.",
"inventoryhud.config.gui.armview.tt.4": "OFF - Вимкнути цифри.",
"inventoryhud.config.gui.armbars": "Шкала:",
"inventoryhud.config.gui.armbars.tt": "Перемикає накладання шкали міцності True/False",
"inventoryhud.config.gui.armhide": "Приховувати вище:",
"inventoryhud.config.gui.armhide.tt": "Приховувати предмет якщо міцність вище цього значення у процентах від 0 до 100",
"inventoryhud.config.gui.armmove": "Перемістити все:",
"inventoryhud.config.gui.armmove.tt.1": "True - змінює позицію всіх предметів одночасно",
"inventoryhud.config.gui.armmove.tt.2": "False - змінює позицію для кожного предмету окремо",
"inventoryhud.config.gui.armempty": "Відобразити пусті:",
"inventoryhud.config.gui.armempty.tt": "Показати/приховати іконку пустих слотів.",
"inventoryhud.config.gui.pos.inv": "Інвентар",
"inventoryhud.config.gui.pos.pot": "Ефекти",
"inventoryhud.config.gui.pos.arm": "Броня",
"inventoryhud.config.gui.pottoggle": "HUD Ефектів",
"inventoryhud.config.gui.pottoggle.tt": "Перемикає відображення HUD Ефектів ON/OFF:",
"inventoryhud.config.gui.potalpha": "Прозорість:",
"inventoryhud.config.gui.potalpha.tt": "Прозорість заднього тла HUD Ефектів від 0 до 100",
"inventoryhud.config.gui.potmini": "Мінімальний режим:",
"inventoryhud.config.gui.potmini.tt": "Перемикає HUD Ефектів в мінімальний режим відображення True/False.",
"inventoryhud.config.gui.potgap": "Відстань:",
"inventoryhud.config.gui.potgap.tt": "Відстань між іконками ефектів від -5 до 5",
"inventoryhud.config.gui.invanimated": "Анімація:",
"inventoryhud.config.gui.invanimated.tt": "Ввімкнення/вимкнення анімації для нещодавно піднятих предметів.",
"inventoryhud.config.gui.invhidebg": "Приховувати тло:",
"inventoryhud.config.gui.invhidebg.tt": "Приховувати тло якщо інвентар порожній.",
"inventoryhud.config.gui.armcount": "Підрахунок предметів:",
"inventoryhud.config.gui.armcount.tt": "Показати накладання кількості предметів в основній/додатковій руці",
"inventoryhud.config.gui.armscale": "Масштаб:",
"inventoryhud.config.gui.armscale.tt": "HUD Броні розмір",
"inventoryhud.config.gui.pothor": "Горизонтальний режим:",
"inventoryhud.config.gui.pothor.tt": "Перемикає в горизонтальний режим відображення",
"inventoryhud.config.gui.bardur": "Тривалість шкали:",
"inventoryhud.config.gui.bardur.tt": "Тривалість в секундах для повної шкали (налаштування для мінімального режиму)",
"key.inventoryhud.toggleall": "Перемикає всі HUD ON/OFF",
"key.inventoryhud.togglepot": "Перемикає HUD Ефектів ON/OFF",
"key.inventoryhud.togglearm": "Перемикає HUD Броні ON/OFF",
"inventoryhud.config.gui.update" : "Доступна нова версія, ",
"inventoryhud.config.gui.updateclick" : "Натисни щоб отримати",
"inventoryhud.config.gui.keepnotify": "Сповіщати більше одного разу:",
"inventoryhud.config.gui.keepnotify.tt": "Якщо False - ти отримаєш сповіщення про нову версію лише раз на версію.",
"inventoryhud.config.gui.hiddeneffects": "Показати приховане:",
"inventoryhud.config.gui.hiddeneffects.tt": "Показувати іконки для прихованих ефектів",
"inventoryhud.config.gui.bl.title": "Редактор Чорного списку",
"inventoryhud.config.gui.blacklist": "Чорной список:",
"inventoryhud.config.gui.blacklist.tt": "Список ефектів із вимкненими знчками",
"inventoryhud.config.gui.blacklistbtn": "Edit",
"inventoryhud.config.gui.bl.add": "Додати ефект",
"inventoryhud.config.gui.bl.delete": "Видалити",
"inventoryhud.config.gui.bl.save": "Зберегти",
"inventoryhud.config.gui.withdebug": "Режим відладки:",
"inventoryhud.config.gui.invdebug.tt": "Показувати HUD Інвентарю коли використовується режим відладки",
"inventoryhud.config.gui.potdebug.tt": "Показувати HUD Ефектів коли використовується режим відладки",
"inventoryhud.config.gui.armdebug.tt": "Показувати HUD Броні коли використовується режим відладки",
"inventoryhud.config.gui.arrowswithoutweapon": "Стріли без зброї:",
"inventoryhud.config.gui.arrowswithoutweapon.tt": "Показувати кількість стріл, навіть якщо ви не тримаєте зброю у руках",
"inventoryhud.config.gui.potionlevels": "Рівні:",
"inventoryhud.config.gui.potionlevels.tt.1": "Якщо 'True' HUD Ефектів буде показувати всі рівні,",
"inventoryhud.config.gui.potionlevels.tt.2": "Замість символу безкінечності для ефектів з рівнем вище ніж дев'ять"
}

**Comment by DmitryLovin** [comment]
Thank you for your contribution, added in inventoryhud v3.4.23
